export const TAROT_DATA = [
    { name: "The Fool", image: "00_the_fool.webp", meaning: "New beginnings, optimism, trust in life" },
    { name: "The Magician", image: "01_the_magician.webp", meaning: "Action, the power to manifest, creativity" },
    { name: "The High Priestess", image: "02_the_high_priestess.webp", meaning: "Inaction, going within, the subconscious" },
    { name: "The Empress", image: "03_the_empress.webp", meaning: "Abundance, nurturing, fertility, life in bloom" },
    { name: "The Emperor", image: "04_the_emperor.webp", meaning: "Structure, stability, rules and power" },
    { name: "The Hierophant", image: "05_the_hierophant.webp", meaning: "Institutions, tradition, society and its rules" },
    { name: "The Lovers", image: "06_the_lovers.webp", meaning: "Partnership, union, duality, choice" },
    { name: "The Chariot", image: "07_the_chariot.webp", meaning: "Direction, control, willpower" },
    { name: "Strength", image: "08_strength.webp", meaning: "Self-discipline, mindfulness, ability to overcome" },
    { name: "The Hermit", image: "09_the_hermit.webp", meaning: "Solitude, looking within, quest for enlightenment" },
    { name: "Wheel of Fortune", image: "10_wheel_of_fortune.webp", meaning: "Fortune, turn of fate, cycle of life" },
    { name: "Justice", image: "11_justice.webp", meaning: "Cause and effect, clarity, truth" },
    { name: "The Hanged Man", image: "12_the_hanged_man.webp", meaning: "Sacrifice, release, new perspectives" },
    { name: "Death", image: "13_death.webp", meaning: "End of a cycle, change, release" },
    { name: "Temperance", image: "14_temperance.webp", meaning: "Balance, moderation, being sensible" },
    { name: "The Devil", image: "15_the_devil.webp", meaning: "Addiction, enslavement, fears that hold you back" },
    { name: "The Tower", image: "16_the_tower.webp", meaning: "Sudden upheaval, broken pride, disaster" },
    { name: "The Star", image: "17_the_star.webp", meaning: "Hope, serenity, the light at the end of the tunnel" },
    { name: "The Moon", image: "18_the_moon.webp", meaning: "Illusion, fear, anxiety, insecurity" },
    { name: "The Sun", image: "19_the_sun.webp", meaning: "Happiness, joy, success, optimism" },
    { name: "Judgement", image: "20_judgement.webp", meaning: "Reflection, reckoning, awakening" },
    { name: "The World", image: "21_the_world.webp", meaning: "Fulfillment, harmony, completion" }
];
